MEMORY
{
  ROM (rwx): ORIGIN = 0x80000000, LENGTH = 256K
  RAM (rwx): ORIGIN = 0x80040000, LENGTH = 128K
}

REGION_ALIAS("REGION_TEXT", ROM);
REGION_ALIAS("REGION_RODATA", ROM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
